services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - pdv-network

  service-backend-pdv:
    container_name: service-backend-pdv
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always
    networks:
      - pdv-network

volumes:
  pgdata:

networks:
  pdv-network:
    name: pdv-network
    driver: bridge
