services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  service-backend-pdv:
    container_name: service-backend-pdv
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
